#### Numpy
- Numpy stands for Numerical Python
- Basic and one of the most important library for numerical computations
- Supports N-dimensional array objects that can be used for processing multidimensional data
- Supports different data-types

##### Using Numpy we can perform

- Mathematical and logical operations on arrays
- Fourier transforms
- Linear algebra operations
- Random number generation

In [1]:
pip list

Package               Version   
--------------------- ----------
altgraph              0.16.1    
attrs                 19.1.0    
backcall              0.1.0     
beautifulsoup4        4.6.3     
bitarray              1.0.1     
bleach                3.1.0     
bs4                   0.0.1     
camelcase             0.2       
captcha               0.3       
certifi               2018.10.15
chardet               3.0.4     
Click                 7.0       
colorama              0.4.1     
cx-Freeze             5.1.1     
cycler                0.10.0    
decorator             4.4.0     
defusedxml            0.6.0     
entrypoints           0.3       
future                0.16.0    
gTTS                  2.0.1     
gTTS-token            1.1.2     
h5py                  2.9.0     
idna                  2.7       
ipykernel             5.1.0     
ipython               7.5.0     
ipython-genutils      0.2.0     
ipywidgets            7.4.2     
jedi                  0.13.3    
Jinja2    

In [2]:
pip show numpy

Name: numpy
Version: 1.15.2
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages
Requires: 
Required-by: seaborn, scipy, scikit-learn, pandas, opencv-python, opencv-contrib-python, matplotlib, Keras, Keras-Preprocessing, Keras-Applications, h5py
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### How to Create arrray
##### 1. using np.array method

- Ordered collection of elements of basic data types of given length
- Syntax: numpy.array(object)

In [3]:
array1=np.array([1,2,3,4,5,6])
print(array1)
type(array1)
print(array1.dtype)

[1 2 3 4 5 6]
int32


In [4]:
array2=np.array([1,2,3,4,6])
print(array2)
type(array2[0])

[1 2 3 4 6]


numpy.int32

In [5]:
type(array2)

numpy.ndarray

In [6]:
print(array2.dtype)

int32


In [7]:
array3=np.array([1,2,3,4.45,6,"string"])
print(array3)
type(array3[1])

['1' '2' '3' '4.45' '6' 'string']


numpy.str_

In [8]:
array4=np.array([1,2,3,4.45,6])
print(array4)
type(array4[1])

[1.   2.   3.   4.45 6.  ]


numpy.float64

##### Important Note - 
- Arrray in python is collection of different datatype elements
- All elements are coerced(converted) to same data type i.e conversion will be done of lower datatype elements to higher datatype elements

In [9]:
arr1=np.array([2,3,5.6,'n'])
print(arr1)
print(type(arr1))
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))

['2' '3' '5.6' 'n']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


##### 2. Generate Array using linespace
- numpy.linspace()- returns equally spaced numbers within the given range based on the sample number
- Syntax:numpy.linspace(start,stop,num)
- start - start of interval range
- stop - end of interval range
- num - number of samples to be generated

- Create array of 10 elements between 0 to 90

In [10]:
a1=np.linspace(0,90,10)
print(a1)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


- Create array of 5 elements between 200 to 390 and show the difference number

In [11]:
a1=np.linspace(start=200,stop=390,num=5,retstep=True)
print(a1)

(array([200. , 247.5, 295. , 342.5, 390. ]), 47.5)


#### 3. Generate arrays using arange( )
- numpy.arange()- returns equally spaced numbers with in the given range based on step size
- Syntax:numpy.arange(start,stop,step)
- start - start of interval range
- stop - end of interval range
- step - step size of interval

In [12]:
a1=np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
a2=np.arange(110,120)
print(a2)

[110 111 112 113 114 115 116 117 118 119]


In [14]:
a3=np.arange(start=110,stop=120,step=3)
print(a3)

[110 113 116 119]


- Create array of elements between 70 to 50 with 5 difference

In [15]:
a4=np.arange(start=70,stop=50,step=-5)
print(a4)

[70 65 60 55]


#### 4. Generate arrays using ones
- numpy.ones()- returns an array of given shape and type filled with ones
- Syntax:numpy.ones(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [16]:
arr4= np.ones(6)
print(arr4)

[1. 1. 1. 1. 1. 1.]


In [17]:
arr5= np.ones((3,7),str)
print(arr5)

[['1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1']]


In [18]:
arr5= np.ones((3,7),int)
print(arr5)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


##### 5. Generate arrays using zeros
- numpy.zeros()- returns an array of given shape and type filled with zeros
- Syntax:numpy.zeros(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [19]:
arr7= np.zeros(6)
print(arr7)

[0. 0. 0. 0. 0. 0.]


In [20]:
arr8= np.zeros((3,7),int)
print(arr8)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


#### 6. Generate arrays using random.rand( )
- numpy.random.rand()- returns an array of given shape filled with random values
- Syntax:numpy.random.rand(shape)
- shape - integer or sequence of integers

In [21]:
# Create 1D array of 5 random elements between 0 to 1
a10=np.random.rand(5)
print(a10)

[0.96794476 0.40095604 0.11991969 0.71807017 0.50998686]


In [22]:
# Create 2D array of 35 random elements between 0 to 1
a11=np.random.rand(7,5)
print(a11)

[[0.12042064 0.4243461  0.55938489 0.8245183  0.23172672]
 [0.65506573 0.61792977 0.17710731 0.94083964 0.84703797]
 [0.24505746 0.03257311 0.70826213 0.9194569  0.81183174]
 [0.12507292 0.77159557 0.85860683 0.8052087  0.03244375]
 [0.53498838 0.03200237 0.08034709 0.51865716 0.36893355]
 [0.33152373 0.26803392 0.3557831  0.08879762 0.29212459]
 [0.0093899  0.16006962 0.83612864 0.23200435 0.68620632]]


In [23]:
# Create 2D array of 35 random int elements between 100 to 150
a12=np.random.randint(100,150,(7,5))
print(a12)

[[135 131 113 121 115]
 [105 104 104 126 114]
 [111 106 136 111 133]
 [120 101 118 110 121]
 [148 128 120 111 127]
 [123 108 143 112 115]
 [142 119 127 137 135]]


In [24]:
a13=np.random.randint(10,20,3)
print(a13)

[17 15 10]


In [25]:
a12=np.random.randint(100,150,(2,2))
print(a12)

[[149 126]
 [110 103]]


In [26]:
# How to check the shape of array
a12.shape

(2, 2)

In [27]:
a13.shape

(3,)

##### 7. Generate arrays using logspace( )
- numpy.logspace()- returns equally spaced numbers based on log scale
- Syntax: numpy.logspace(start,stop,num,endpoint,base,dtype)
- start, stop,
- num - number of samples to generate (default :50),
- endpoint- if true, stop is the last sample,
- base - base of the log space (default :10.0),
- dtype- type of output array
- Generate array of 5 samples with base 10

In [28]:
a14=np.logspace(start=1,stop=10,num=5,endpoint=True, base=10)

In [29]:
a14

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

##### Advatanges of Array - 

1. Speed - Array is faster than list
2. Memory Storage - Array takes less memory than list

In [30]:
import time

In [31]:
# Consider case for List
py_list=[i for i in range(100000)]
start=time.time()
py_list=[i+2 for i in py_list]
stop=time.time()
print(stop-start)

0.017000913619995117


In [32]:
# Consider case for Numpy Array
py_arr=np.array([i for i in range(1000000)])
start=time.time()
py_arr=py_arr+2
stop=time.time()
print(stop-start)

0.0030002593994140625


##### Storage Space - 

In [33]:
import sys

In [34]:
a1=np.arange(100)
print(type(a1))
print(a1.size)
print("Total space taken by a1 is",a1.itemsize*100)

<class 'numpy.ndarray'>
100
Total space taken by a1 is 400


In [35]:
l1=[i for i in range(100)]

In [36]:
len(l1)

100

In [37]:
print("Total size taken by l1 =",sys.getsizeof(l1[0])*len(l1))

Total size taken by l1 = 1200


- Operations

Reshape - We can change shape of arrays

In [38]:
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a.shape)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)


In [39]:
b=a.reshape(4,2)
print(b)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [40]:
b.shape

(4, 2)

In [41]:
c=b.reshape(1,8)
print(c)

[[1 2 3 4 6 7 8 9]]


In [42]:
c=np.arange(11,20).reshape(3,3)
print(c)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [48]:
c

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [56]:
# Subseting array - slicing
d=c[0:2,0:2]

In [51]:
d

array([[11, 12],
       [14, 15]])

In [52]:
d[1,1]=55
d

array([[11, 12],
       [14, 55]])

In [53]:
c

array([[11, 12, 13],
       [14, 55, 16],
       [17, 18, 19]])

In [54]:
e=c[2]

In [55]:
e

array([17, 18, 19])

##### addition in Numpy

In [57]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
print(a.shape)
print(a.size)

(3, 3)
9


In [61]:
print(np.sum(a))
print(a.sum())

45
45


In [64]:
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[12 15 18]
[ 6 15 24]


In [65]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [67]:
print("addditon of a1 and a2 is\n",np.add(a1,a2))

addditon of a1 and a2 is
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [69]:
print("subtract of a1 and a2 is\n",np.subtract(a1,a2))

subtract of a1 and a2 is
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [70]:
print("mul of a1 and a2 is\n",np.multiply(a1,a2))

mul of a1 and a2 is
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [72]:
print("divide of a1 and a2 is\n",np.divide(a2,a1))

divide of a1 and a2 is
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [73]:
print("remainder of a1 and a2 is\n",np.remainder(a2,a1))

remainder of a1 and a2 is
 [[0 0 1]
 [2 0 4]
 [3 2 1]]


In [74]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
np.transpose(a1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [76]:
a1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [89]:
a3=np.append(a1,[[10,11,12]],axis=0)
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
a3.shape

(4, 3)

In [102]:
z=np.array([[21,22,23,24]])

In [105]:
y=np.transpose(z)
y

array([[21],
       [22],
       [23],
       [24]])

In [106]:
a4=np.append(a3,y,axis=1)

In [107]:
a4

array([[ 1,  2,  3, 21],
       [ 4,  5,  6, 22],
       [ 7,  8,  9, 23],
       [10, 11, 12, 24]])

In [108]:
a5=a4[1:3,1:3]
a5

array([[5, 6],
       [8, 9]])

In [109]:
a6=a4[1:3,:]
a6

array([[ 4,  5,  6, 22],
       [ 7,  8,  9, 23]])

In [110]:
a10=np.array([1,2,3,4]).reshape(4,1)

In [111]:
a10

array([[1],
       [2],
       [3],
       [4]])

#### Matrix

- rectangular arrangment of numbers which will have rows and columns

In [113]:
mat1=np.matrix("1,2,3;4,5,6;7,8,9")
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [114]:
mat1.size

9

In [115]:
mat1.shape

(3, 3)

In [116]:
mat2=np.matrix("11,12,13;14,15,16;17,18,19")
mat2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [117]:
np.add(mat1,mat2)

matrix([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]])

In [118]:
np.subtract(mat1,mat2)

matrix([[-10, -10, -10],
        [-10, -10, -10],
        [-10, -10, -10]])

In [123]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [124]:
mat2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [121]:
# this is will give matrix multiplication according to maths rules
np.dot(mat1,mat2)

matrix([[ 90,  96, 102],
        [216, 231, 246],
        [342, 366, 390]])

In [122]:
# This is will element wise multiplication
np.multiply(mat1,mat2)

matrix([[ 11,  24,  39],
        [ 56,  75,  96],
        [119, 144, 171]])

In [125]:
c=np.matrix("1,2,3;5,6,7")
d=np.matrix("1,2,3;4,5,6;7,8,9;11,12,13")
print(c)
print(d)

[[1 2 3]
 [5 6 7]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


In [126]:
c.shape

(2, 3)

In [127]:
d.shape

(4, 3)

In [128]:
np.dot(c,d)

ValueError: shapes (2,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [129]:
np.divide(mat1,mat2)

matrix([[0.09090909, 0.16666667, 0.23076923],
        [0.28571429, 0.33333333, 0.375     ],
        [0.41176471, 0.44444444, 0.47368421]])

In [130]:
np.remainder(mat1,mat2)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)

#### Linear Algebra

In [131]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [132]:
mat2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

##### Determinant of Matrix

In [133]:
det_mat1=np.linalg.det(mat1)
det_mat1

6.66133814775094e-16

In [134]:
m3=np.matrix("5,2;3,4")

In [135]:
m3

matrix([[5, 2],
        [3, 4]])

In [136]:
det=np.linalg.det(m3)
det

13.999999999999996

##### rank of Matrix

In [144]:
rank_m1=np.linalg.matrix_rank(mat1)
rank_m2=np.linalg.matrix_rank(mat2)
print(rank_m1)
print(rank_m2)

2
2


In [143]:
rank_m3

2

##### Inverse of Matrix

In [146]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [147]:
mat1_inv=np.linalg.inv(mat1)
mat1_inv

matrix([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
        [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
        [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

#### Linear Equations

In [148]:
A=np.matrix("3,1,2;3,2,5;6,7,8")
A

matrix([[3, 1, 2],
        [3, 2, 5],
        [6, 7, 8]])

In [149]:
A.shape

(3, 3)

In [150]:
b=np.matrix("2;-1;3")

In [151]:
b

matrix([[ 2],
        [-1],
        [ 3]])

In [152]:
result=np.linalg.solve(A,b)
result

matrix([[ 1.24242424],
        [ 0.81818182],
        [-1.27272727]])